#Classification with Neural Network
The Iris dataset consists of sepal_length, sepal_width, petal_length, petal_width, and species.

Adapted from https://gist.github.com/NiharG15/cd8272c9639941cf8f481a7c4478d525

In [ ]:
import numpy as np
import tensorflow as tf

from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical

In [ ]:
# load dataset
iris = load_iris()

print('Example data: ')
print(iris.data[:5])
print('Example labels: ')
print(iris.target[:5])

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
[0 0 0 0 0]


##Preprocessing

In [ ]:
# define features and target variables
X = iris.data
y = iris.target.reshape(-1, 1)

In [ ]:
# one hot encoding
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y)

print(y[:5])

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [ ]:
# split data for training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True)

print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

120
30
120
30


## Building the model

In [ ]:
# define the model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, input_shape=(4,), activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
  ])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['acc'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                50        
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 3)                 33        
                                                                 
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# train the model
model.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
12/12 [==============================] - 1s 2ms/step - loss: 0.9996 - acc: 0.3250
Epoch 2/100
12/12 [==============================] - 0s 2ms/step - loss: 0.9331 - acc: 0.5750
Epoch 3/100
12/12 [==============================] - 0s 3ms/step - loss: 0.8680 - acc: 0.6583
Epoch 4/100
12/12 [==============================] - 0s 4ms/step - loss: 0.8125 - acc: 0.6583
Epoch 5/100
12/12 [==============================] - 0s 2ms/step - loss: 0.7677 - acc: 0.6583
Epoch 6/100
12/12 [==============================] - 0s 2ms/step - loss: 0.7250 - acc: 0.6667
Epoch 7/100
12/12 [==============================] - 0s 2ms/step - loss: 0.6851 - acc: 0.8500
Epoch 8/100
12/12 [==============================] - 0s 2ms/step - loss: 0.6454 - acc: 0.9083
Epoch 9/100
12/12 [==============================] - 0s 2ms/step - loss: 0.6079 - acc: 0.9250
Epoch 10/100
12/12 [==============================] - 0s 2ms/step - loss: 0.5694 - acc: 0.9333
Epoch 11/100
12/12 [==============================] - 0s 3m

## Evaluation

In [ ]:
# evaluate model with test data
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.11231517791748047
Test accuracy: 0.9666666388511658


In [ ]:
# make predictions
y_pred = model.predict(X_test)
print(y_pred)

[[1.74893357e-03 8.87365639e-01 1.10885434e-01]
 [9.98334229e-01 1.43874576e-03 2.27117212e-04]
 [2.16603240e-07 3.68881738e-05 9.99962926e-01]
 [1.83390186e-03 9.14233685e-01 8.39323923e-02]
 [7.13101472e-04 9.69169855e-01 3.01171131e-02]
 [9.96606112e-01 2.92505510e-03 4.68822720e-04]
 [8.58332030e-03 9.81120527e-01 1.02960560e-02]
 [7.02118909e-04 5.21197855e-01 4.78099912e-01]
 [1.46217947e-03 6.50865138e-01 3.47672701e-01]
 [2.59773131e-03 9.88042951e-01 9.35933087e-03]
 [1.00234780e-03 4.69686866e-01 5.29310822e-01]
 [9.94940639e-01 4.29647323e-03 7.62908137e-04]
 [9.98395264e-01 1.36559282e-03 2.39073983e-04]
 [9.94815528e-01 4.44575399e-03 7.38680479e-04]
 [9.98042703e-01 1.65020558e-03 3.07104638e-04]
 [1.22104038e-03 9.65338290e-01 3.34406346e-02]
 [1.77232723e-05 2.39133369e-03 9.97591019e-01]
 [2.08857376e-03 9.85449255e-01 1.24622127e-02]
 [2.64904904e-03 8.18495989e-01 1.78854942e-01]
 [2.21702521e-05 2.89800321e-03 9.97079790e-01]
 [9.93033648e-01 5.98179502e-03 9.845453

In [ ]:
# get class from probabilities
actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)

print(f"Actual: {actual}")
print(f"Predicted: {predicted}")

Actual: [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
Predicted: [1 0 2 1 1 0 1 1 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
